import { describe, it, expect } from "vitest";
import { generateClaudeMD } from "./generate-claude-md";
import { DEFAULTS } from "./defaults";
import type { Config } from "./types";

function makeConfig(overrides: Partial<Config> = {}): Config {
  return { ...DEFAULTS, ...overrides };
}

describe("generateClaudeMD", () => {
  it("produces valid markdown with 700+ lines from default config", () => {
    const result = generateClaudeMD(makeConfig());
    const lines = result.split("\n");
    expect(lines.length).toBeGreaterThan(700);
    expect(result).toContain("# AI Business Opportunity Research System v4.0");
    expect(result).toContain("Generated by IdeaForge");
  });

  it("omits direction section when direction is empty", () => {
    const result = generateClaudeMD(makeConfig({ direction: "" }));
    expect(result).not.toContain("## 🧭 DIRECTION FOR THIS RUN");
  });

  it("includes direction section when direction is set", () => {
    const result = generateClaudeMD(makeConfig({ direction: "Focus on AI tutoring" }));
    expect(result).toContain("## 🧭 DIRECTION FOR THIS RUN");
    expect(result).toContain("Focus on AI tutoring");
    expect(result).toContain("MUST prioritize this direction");
  });

  it("omits principles section when all principles are off", () => {
    const config = makeConfig({
      principles: DEFAULTS.principles.map((p) => ({ ...p, on: false })),
    });
    const result = generateClaudeMD(config);
    expect(result).not.toContain("## Core Principles");
  });

  it("includes principles section when at least one is active", () => {
    const result = generateClaudeMD(makeConfig());
    expect(result).toContain("## Core Principles");
    expect(result).toContain("Prefer ideas where value is easy to quantify");
  });

  it("shows excluded marker when profile section is off", () => {
    const config = makeConfig({
      sections: { ...DEFAULTS.sections, profile: false },
    });
    const result = generateClaudeMD(config);
    expect(result).toContain("Operator Profile ✗");
    expect(result).not.toContain("### Background & Advantages");
  });

  it("keeps constraints in output even when profile is off", () => {
    const config = makeConfig({
      sections: { ...DEFAULTS.sections, profile: false },
    });
    const result = generateClaudeMD(config);
    expect(result).toContain("Operator Profile ✗");
    // Constraints from auto-reject and user constraints still appear
    expect(result).toContain("Auto-REJECT");
    expect(result).toContain("No sales calls or demos → REJECT");
  });

  it("omits feed section when feed is empty", () => {
    const result = generateClaudeMD(makeConfig({ feed: [] }));
    expect(result).not.toContain("## Input Feed");
  });

  it("includes feed section when pending items exist", () => {
    const config = makeConfig({
      feed: [
        { id: "f1", t: "AI homework helper", type: "idea", vertical: "Education", status: "pending" },
        { id: "f2", t: "Rising AI tutoring demand", type: "signal", vertical: null, status: "pending" },
      ],
    });
    const result = generateClaudeMD(config);
    expect(result).toContain("## Input Feed");
    expect(result).toContain("AI homework helper");
    expect(result).toContain("💡 IDEA SEED");
    expect(result).toContain("📰 SIGNAL");
  });

  it("omits feed section when all items are explored", () => {
    const config = makeConfig({
      feed: [
        { id: "f1", t: "Old idea", type: "idea", vertical: null, status: "explored" },
      ],
    });
    const result = generateClaudeMD(config);
    expect(result).not.toContain("## Input Feed");
  });

  it("shows simplified founders section when team is excluded", () => {
    const config = makeConfig({
      sections: { ...DEFAULTS.sections, team: false },
    });
    const result = generateClaudeMD(config);
    expect(result).toContain("Creative Founders ✗");
    expect(result).toContain("simplified generation without persona orchestration");
    expect(result).not.toContain("The Founding Team");
  });

  it("shows scoring excluded marker when scoring is off", () => {
    const config = makeConfig({
      sections: { ...DEFAULTS.sections, scoring: false },
    });
    const result = generateClaudeMD(config);
    expect(result).toContain("Scoring ✗");
    expect(result).not.toContain("### Scoring Criteria");
  });

  it("criteria weights appear correctly in scoring table", () => {
    const result = generateClaudeMD(makeConfig());
    expect(result).toContain("| **GTM Strategy** | 30%");
    expect(result).toContain("| **Automation** | 20%");
    expect(result).toContain("| **Economics** | 20%");
    expect(result).toContain("| **Differentiation** | 15%");
    expect(result).toContain("| **Buildability** | 15%");
  });

  it("includes static sections always (trend scouts, file locations, etc.)", () => {
    const result = generateClaudeMD(makeConfig());
    expect(result).toContain("## Team 1: Trend Scouts");
    expect(result).toContain("## Team 1B: Competitor Scout");
    expect(result).toContain("## System Architecture");
    expect(result).toContain("## Daily Execution");
    expect(result).toContain("## ⚠️ MANDATORY: Automatic Pitch Deck Generation");
    expect(result).toContain("## ⚠️ CRITICAL: File Locations");
    expect(result).toContain("## Daily Report Format");
    expect(result).toContain("## Idea Memory System");
    expect(result).toContain("## Execution Commands");
  });

  it("shows EXPLORE MODE for novelty >= 70", () => {
    const result = generateClaudeMD(makeConfig({ novelty: 80 }));
    expect(result).toContain("**EXPLORE MODE:**");
  });

  it("shows BALANCED MODE for novelty 40-69", () => {
    const result = generateClaudeMD(makeConfig({ novelty: 50 }));
    expect(result).toContain("**BALANCED MODE:**");
  });

  it("shows REFINE MODE for novelty < 40", () => {
    const result = generateClaudeMD(makeConfig({ novelty: 20 }));
    expect(result).toContain("**REFINE MODE:**");
  });

  it("changes mission for side hustle business model", () => {
    const config = makeConfig({
      bizPreset: "side_hustle",
      bizType: "hybrid",
      bizTeam: "solo_ai",
      bizAI: "enhanced",
      bizTouch: "low",
      bizInvest: "light",
    });
    const result = generateClaudeMD(config);
    expect(result).toContain("Online + offline hybrid");
    expect(result).toContain("AI-enhanced");
    expect(result).toContain("Low-touch");
    expect(result).toContain("$500-5K startup investment");
  });

  it("shows verticals distribution when verticals are enabled", () => {
    const result = generateClaudeMD(makeConfig());
    expect(result).toContain("## Verticals");
    expect(result).toContain("| Education | 25% |");
    expect(result).toContain("| Wildcard | 5% |");
  });

  it("shows focus mode when active", () => {
    const config = makeConfig({ focusMode: "Education" });
    const result = generateClaudeMD(config);
    expect(result).toContain("FOCUS MODE: Education");
    expect(result).toContain("All 15 ideas this run should be in or adjacent to **Education**");
  });

  it("omits verticals section when verticals toggle is off", () => {
    const config = makeConfig({
      sections: { ...DEFAULTS.sections, verticals: false },
    });
    const result = generateClaudeMD(config);
    expect(result).not.toContain("## Verticals");
  });

  it("includes advisor table with weights", () => {
    const result = generateClaudeMD(makeConfig());
    expect(result).toContain("| `advisor_skeptic` | 1.5x |");
    expect(result).toContain("| `advisor_gtm` | 1.5x |");
    expect(result).toContain("| `advisor_advocate` | 0.8x |");
  });

  it("includes GTM Advisor Deep Dive when veto advisor is active", () => {
    const result = generateClaudeMD(makeConfig());
    expect(result).toContain("GTM Advisor Deep Dive");
    expect(result).toContain("VETO POWER");
  });

  it("includes all 13 founders when all are active", () => {
    const result = generateClaudeMD(makeConfig());
    expect(result).toContain("Maya Chen");
    expect(result).toContain("Derek Kim");
    expect(result).toContain("Nina Patel");
    expect(result).toContain("Kai Nakamura");
    expect(result).toContain("Priya Shah");
    expect(result).toContain("Tony Vasquez");
  });

  it("excludes specific founders when toggled off", () => {
    const config = makeConfig({
      founders: DEFAULTS.founders.map((f) =>
        f.id === "maya" ? { ...f, on: false } : f
      ),
    });
    const result = generateClaudeMD(config);
    expect(result).not.toContain("`maya` - Maya Chen");
    expect(result).toContain("`derek` - Derek Kim");
  });

  it("includes idea mix table with correct counts", () => {
    const result = generateClaudeMD(makeConfig({ mix: { trend: 8, pattern: 4, wild: 3 } }));
    expect(result).toContain("| **🔥 Trend-Driven** | 8 |");
    expect(result).toContain("| **🎯 Pattern-Based** | 4 |");
    expect(result).toContain("| **🎲 Wild Cards** | 3 |");
  });

  it("physical business type adds supply chain scouting", () => {
    const config = makeConfig({ bizType: "physical" });
    const result = generateClaudeMD(config);
    expect(result).toContain("supply chain");
    expect(result).toContain("Amazon/Etsy");
  });
});
