import type { Config, BizType, BizTeam, BizAI, BizTouch, BizInvest, Budget } from "./types";

export function generateClaudeMD(cfg: Config): string {
  const {
    direction = "",
    principles = [],
    bizType = "digital",
    bizTeam = "solo_ai",
    bizAI = "native",
    bizTouch = "self_serve",
    bizInvest = "bootstrap",
    revenue = 5000,
    budget = "low",
    ideasPer = 15,
    deckCut = 80,
    novelty = 70,
    mix = { trend: 6, pattern: 4, wild: 4 },
    sections = { profile: true, team: true, scoring: true, feed: true, verticals: true },
    founderName: _founderName,
    founderRole = "Creative Director + Product Strategist",
    founderTime = "1 day/week",
    skills = [],
    filters = [],
    founders = [],
    advisors = [],
    verts = [],
    focusMode = null,
    criteria = [],
    constraints = [],
    feed = [],
  } = cfg;

  const date = new Date().toISOString().split("T")[0];
  const activePrinciples = principles.filter((p) => p.on);
  const activeFounders = founders.filter((f) => f.on);
  const activeAdvisors = advisors.filter((a) => a.on);
  const activeVerts = verts.filter((v) => v.on);
  const pendingFeed = feed.filter((f) => f.status === "pending");
  const vetoAdvisors = activeAdvisors.filter((a) => a.veto);

  // Labels
  const L: {
    type: Record<BizType, string>;
    team: Record<BizTeam, string>;
    ai: Record<BizAI, string>;
    touch: Record<BizTouch, string>;
    invest: Record<BizInvest, string>;
    budget: Record<Budget, string>;
  } = {
    type: { digital: "Digital-first", physical: "Physical products", hybrid: "Online + offline hybrid", service: "Service/agency" },
    team: { solo: "Solo operator", solo_ai: "Solo operator + AI agents", small: "Small team (2-3 people)", flex: "Flexible" },
    ai: { native: "99% automatable with AI agents/tools", enhanced: "AI-enhanced (AI gives meaningful competitive edge)", optional: "AI-optional (helpful but not core)", none: "No AI constraint" },
    touch: { self_serve: "Self-serve (customer buys without talking to anyone)", low: "Low-touch (email/async support only)", medium: "Medium-touch (some calls/demos OK)", high: "High-touch (consulting/custom work OK)" },
    invest: { bootstrap: "<$500 startup cost", light: "$500-5K startup investment", moderate: "$5K-25K startup investment", flex: "Flexible budget" },
    budget: { zero: "$0 — organic only", low: "$100-500/month", medium: "$500-2K/month", high: "$2K+/month" },
  };

  // Auto-reject rules based on business model
  const autoRejects: string[] = [];
  if (bizTouch === "self_serve") autoRejects.push("Requires sales calls or demos");
  if (bizTouch === "self_serve" || bizTouch === "low") autoRejects.push("Requires manual outreach");
  if (bizInvest === "bootstrap") autoRejects.push(">$500 startup cost");
  autoRejects.push("Requires licenses (legal/medical/financial advice)");
  if (bizTeam === "solo" || bizTeam === "solo_ai") autoRejects.push("Requires existing audience");

  // Constraint text
  const allConstraints = [
    ...autoRejects.map((r) => `- ${r} → REJECT`),
    ...constraints.filter((c) => c.on).map((c) => `- ${c.t} → REJECT`),
  ];

  // ═══ BUILD THE DOCUMENT ═══
  let md = "";

  // ── Header ──
  md += `# AI Business Opportunity Research System v4.0
*Generated by IdeaForge · ${date}*

`;

  // ── Direction (if set) ──
  if (direction.trim()) {
    md += `## 🧭 DIRECTION FOR THIS RUN

> ${direction.trim()}

**The creative team MUST prioritize this direction above all other inputs.** This shapes which trends to scout, which ideas to generate, and how to evaluate them. If the direction conflicts with vertical weights, the direction wins.

---

`;
  }

  // ── Principles (if any active) ──
  if (activePrinciples.length > 0) {
    md += `## Core Principles

These are persistent values that guide every idea from inception through scoring:

${activePrinciples.map((p) => `- **${p.t}**`).join("\n")}

Every founder, every advisor, and every scoring decision should reflect these principles.

---

`;
  }

  // ── Mission ──
  md += `## Mission

Discover, evaluate, and validate business opportunities that are:
- ${L.ai[bizAI]}
- High probability of $${revenue.toLocaleString()}/month profit (prefer 99% chance at $${revenue.toLocaleString()} over 50% chance at $${(revenue * 20).toLocaleString()})
- ${L.type[bizType]}
- ${L.touch[bizTouch]}
- ${L.team[bizTeam]}
- ${L.invest[bizInvest]}
- Marketing budget: ${L.budget[budget]}
${activePrinciples.some((p) => p.t.toLowerCase().includes("impact")) ? "- Purpose-driven where possible — prefer ideas that create real impact for underserved people\n" : ""}
---

`;

  // ── Novelty Setting ──
  md += `## Novelty Setting: ${novelty}%

`;
  if (novelty >= 70) {
    md += `**EXPLORE MODE:** Prioritize novel, unexpected ideas. Actively penalize similarity to past ideas in idea_memory_active.json. Push into unexplored verticals and business models. If an idea feels "safe" or "obvious," challenge yourself to find something more creative. Reward contrarian thinking and unusual combinations.

`;
  } else if (novelty >= 40) {
    md += `**BALANCED MODE:** Mix of novel exploration and refinement of proven patterns. Some ideas should iterate on what's working, others should break new ground.

`;
  } else {
    md += `**REFINE MODE:** Iterate on winning patterns from past runs. Produce variations and improvements of highest-scoring idea types. Focus on making good ideas great rather than finding entirely new concepts.

`;
  }
  md += `---

`;

  // ── Operator Profile ──
  if (sections.profile) {
    md += `## Operator Profile

### Background & Advantages
${skills.length > 0 ? skills.map((s) => `- ${s}`).join("\n") : "- (No specific skills listed)"}

### Role: ${founderRole} ONLY
**You do:** Strategic direction, quality control review, go/no-go decisions, approve marketing content
**You don't do:** ${bizTouch === "self_serve" ? 'Sales calls, manual outreach, account management, hands-on delivery, being the "face"' : bizTouch === "low" ? "Heavy sales, account management, hands-on delivery" : "Hands-on delivery at scale"}

${bizTouch === "self_serve" ? "If an idea requires sales calls or manual selling → automatic reject.\n\n" : ""}### Constraints
- ~${founderTime} total time available
- No existing audience
- Has: domains, hosting, tools, Claude Pro/API access

### Filters
${filters.length > 0 ? `**AVOID:** ${filters.join(", ")}` : "**AVOID:** (No specific filters set)"}

**OK (clarification):**
- Tools for traders/investors (tracking, analysis, alerts, journaling) — no advice, just tools
- Educational content about investing concepts — no specific recommendations

**OPPORTUNITY SIGNALS:** Underserved populations with money, poor UX in existing market, unsexy niches VCs ignore

---

`;
  } else {
    md += `## Operator Profile ✗ (excluded — no operator constraints applied)

---

`;
  }

  // ── System Architecture ──
  md += `## System Architecture

\`\`\`
DAILY:
Inbox → Trend Scouts → Competitor Scout → Creative Founders (${ideasPer} ideas) → Advisors → [Iteration] → Pitch Decks (${deckCut}%+) → Daily Report

PITCH DECKS (AUTOMATIC FOR ${deckCut}%+):
1. Read /templates/pitch-deck-template.md
2. Generate deck for TOP 6 ideas scoring ${deckCut}%+
3. Save to ~/Projects/ai-business-research/pitch-decks/[name]-deck.html (ROOT LEVEL!)

REFLECTION (On Request):
For reflection commands → Read /templates/reflection-commands.md

AI INSIGHTS (On Request):
For insights analysis → Read /templates/ai-insights-template.md
\`\`\`

---

## Inbox System

### Structure
\`\`\`
/inbox/
├── ideas/      ← Business ideas
├── research/   ← News, tools, trends
└── processed/  ← Moved here after processing
\`\`\`

### How It Works
1. Drop file in \`/inbox/ideas/\` or \`/inbox/research/\`
2. Daily run processes all files
3. Ideas → developed and evaluated
4. Research → context AND mined for opportunities
5. Files moved to \`/processed/\`

---

`;

  // ── Input Feed (Seeds & Signals) ──
  if (sections.feed && pendingFeed.length > 0) {
    const feedTypes: Record<string, string> = { idea: "💡 IDEA SEED", signal: "📰 SIGNAL", data: "📊 DATA POINT", url: "🔗 URL TO MINE" };
    md += `## Input Feed (Seeds & Signals)

Process these items during today's run. Each has a type that determines how to use it:

${pendingFeed.map((f) => `- **${feedTypes[f.type] || "ITEM"}:** ${f.t}${f.vertical ? ` [${f.vertical}]` : ""}`).join("\n")}

**Processing rules:**
- 💡 Ideas → Develop and evaluate through the full pipeline
- 📰 Signals → Feed to Trend Scouts as additional context, mine for opportunities
- 📊 Data → Use as evidence in ideation and scoring
- 🔗 URLs → Read, extract insights, mine for business opportunities

---

`;
  }

  // ── Trend Scouts ──
  md += `## Team 1: Trend Scouts

### 🔥 CRITICAL ROLE: Trend Scouts DRIVE Idea Generation

Trends are not just context — they are the PRIMARY INPUT for ideation. The Creative Founders should be reacting to what Trend Scouts find, not generating ideas in a vacuum.

### Agents
| Agent | Focus |
|-------|-------|
| \`tech_scout\` | New AI tools, APIs, platforms (last 48h) — **What's newly possible?** |
| \`capability_scout\` | Breakthroughs that unlock new products — **What couldn't we build yesterday?** |
| \`market_scout\` | Gaps, pain points, emerging needs — **Who's underserved?** |
| \`ux_gap_scout\` | Poor design in existing solutions — **Where's the opportunity?** |
| \`acquisition_scout\` | New distribution channels — **How can we reach people?** |

### Daily Tasks
1. Process \`/inbox/research/\` first
2. Search for new AI tools/capabilities (last 24-48h)
3. **Flag specific "idea triggers"** — things that could spawn businesses
4. Identify arbitrage opportunities
5. Flag markets with poor UX
6. Search across DIVERSE verticals (not just B2B SaaS)
${bizType === "physical" || bizType === "hybrid" ? "7. Scout physical product opportunities, e-commerce trends, and supply chain innovations" : ""}${novelty >= 70 ? "\n7. Actively seek trends in UNEXPLORED verticals — avoid retreading familiar territory" : ""}

### Output: \`trends.json\`
\`\`\`json
{
  "trend": "Description",
  "source": "Where found",
  "idea_trigger": "What business could this enable?",
  "potential_audiences": ["audience1", "audience2"],
  "urgency": "high|medium|low"
}
\`\`\`

---

## Team 1B: Competitor Scout

### Mission
For every potential opportunity, research existing competition BEFORE idea development.

### Output Per Opportunity
\`\`\`json
{
  "opportunity": "description",
  "existing_competitors": [
    {"name": "", "what_they_do": "", "pricing": "", "weaknesses": ""}
  ],
  "saturation_level": "oversaturated|competitive|moderate|underserved|blue_ocean",
  "gaps_identified": ["gap1", "gap2"],
  "differentiation_angle": "how we'd be different",
  "barrier_to_entry": "low|medium|high"
}
\`\`\`

### Saturation Rules
- **Oversaturated**: 10+ well-funded competitors, no clear gap → SKIP
- **Competitive**: Several competitors but clear differentiation possible → PROCEED WITH CAUTION
- **Moderate**: Few competitors, obvious gaps → GOOD
- **Underserved**: 1-2 weak competitors or none → GREAT
- **Blue Ocean**: No one doing this yet, clear need → EXCELLENT

---

`;

  // ── Creative Founders ──
  if (sections.team) {
    md += `## Team 2: Creative Founders

### The Founding Team

This isn't a committee — it's a **founding team** with complementary skills who build on each other's ideas. Each founder has a distinct background that shapes how they see opportunities.

---

`;

    // Group by category
    const catLabels: Record<string, string> = {
      serial: "🎯 THE SERIAL ENTREPRENEURS (Pattern Recognition)",
      creative: "🎨 THE CREATIVE OUTSIDERS (Fresh Perspectives)",
      operator: "🚀 THE OPERATORS (Execution Focus)",
      gtm: "📣 THE GTM SPECIALISTS (Go-To-Market & AI Marketing)",
      futurist: "🔥 THE FUTURIST (Trend Translation)",
    };
    const catIntros: Record<string, string> = {
      gtm: "**These founders focus on the hardest problem: finding and converting customers.**\n",
    };

    for (const [cat, label] of Object.entries(catLabels)) {
      const catFounders = activeFounders.filter((f) => f.cat === cat);
      if (catFounders.length === 0) continue;

      md += `### ${label}

${catIntros[cat] || ""}`;

      for (const f of catFounders) {
        md += `#### \`${f.id}\` - ${f.name}
**Background:** ${f.bg}
**Superpower:** ${f.power}
**Lens:** "${f.lens}"
**Asks:**
${f.asks.map((a) => `- "${a}"`).join("\n")}
${f.knows ? `\n**Knows:**\n${f.knows.map((k) => `- ${k}`).join("\n")}` : ""}

`;
      }
      md += `---

`;
    }

    // Ideation process
    md += `### 💡 COLLABORATIVE IDEATION PROCESS

**The founders don't work in silos. They build on each other.**

#### Phase 1: Seeding (Individual)
Each founder generates 2-3 raw ideas based on today's trends through their unique lens.

#### Phase 2: Building (Pairs)
Founders pair up to strengthen ideas — combining perspectives for stronger concepts.

#### Phase 3: Challenging (Full Team)
The full team stress-tests the top ideas. Each founder asks their signature question. Ideas get strengthened, not killed. Look for "yes, and..." not "no, because..."

#### Phase 4: Final Selection
Select ${ideasPer} ideas that:
- Survived the gauntlet
- Represent diverse approaches
- Include at least ${mix.trend} trend-driven ideas
- Include at least ${mix.wild} wild cards
${novelty >= 70 ? '- **NOVELTY CHECK:** At least 50% of ideas must be in verticals or business models NOT seen in idea_memory_active.json' : ""}

---

### IDEA MIX

| Category | Count | Description |
|----------|-------|-------------|
| **🔥 Trend-Driven** | ${mix.trend} | Tied to something new in last 48h |
| **🎯 Pattern-Based** | ${mix.pattern} | Based on proven market patterns |
| **🎲 Wild Cards** | ${mix.wild} | Unexpected, creative, contrarian |

---

`;
  } else {
    md += `## Creative Founders ✗ (excluded — simplified generation without persona orchestration)

Generate ${ideasPer} business ideas based on trend research and market analysis. Mix: ${mix.trend} trend-driven, ${mix.pattern} pattern-based, ${mix.wild} wild cards.

---

`;
  }

  // ── Required Output Per Idea ──
  md += `### Required Output Per Idea

1. Business concept (specific, 1 paragraph)
${sections.team ? "2. **Which founder(s) originated this** and why\n3. **What trend/insight inspired this** (for trend-driven ideas)" : "2. What trend/insight inspired this"}
4. Target customer + pain point
5. How ${bizAI === "native" ? "AI/automation delivers solution" : bizAI === "enhanced" ? "AI enhances the solution" : "the solution works"}
6. Revenue model + path to $${revenue.toLocaleString()}/month
7. ${bizAI === "native" ? "Automation stack (specific tools)" : "Technology stack"}
8. ${bizTeam === "solo" || bizTeam === "solo_ai" ? 'The 1% human involvement' : "Team requirements and roles"}
9. Time to first revenue
10. Startup costs
11. **Competitor landscape** (from Competitor Scout)
12. **Differentiation angle**
13. **GTM STRATEGY (Detailed):**
    - **Primary channel** + why it fits this audience
    - **Secondary channel** + timeline
    - **Specific tools** (from GTM stack list)
    - **Time to first paying customer** (must be <60 days)
    - **Target CAC** and how to achieve it
    - **Launch sequence** (week 1-4 plan)
${sections.team ? `14. **What \`priya_performance\` says:** (ad creative angle, if applicable)
15. **What \`marcus_community\` says:** (organic/community angle)` : ""}

---

### Acquisition ${bizTouch === "self_serve" ? "Must Be Automated" : "Strategy"}

**GOOD:** SEO/content, Paid ads, Marketplace listings, Affiliate programs, Email sequences, Viral mechanics${bizTouch !== "self_serve" ? ", Partnerships, Referrals" : ""}${bizType === "physical" ? ", Amazon/Etsy/Shopify marketplace, Wholesale" : ""}

**BAD (auto-reject):** ${bizTouch === "self_serve" ? "Cold calling, Sales demos, LinkedIn outreach, Networking, Enterprise sales" : bizTouch === "low" ? "Enterprise sales, Heavy consulting sales" : "No restrictions on sales methods"}

---

### Quality Filters

**Auto-REJECT (real blockers):**
${allConstraints.join("\n")}

**Soft Filters (penalize but don't auto-reject):**
- Saturated market → Check if new angle exists
- Seems small → Check if highly profitable niche
- Unusual vertical → Might be opportunity

---

`;

  // ── Verticals ──
  if (sections.verticals) {
    md += `## Verticals

`;
    if (focusMode) {
      md += `### 🎯 FOCUS MODE: ${focusMode}

All ${ideasPer} ideas this run should be in or adjacent to **${focusMode}**. Explore different angles, sub-niches, and adjacent problems within this vertical.

`;
    } else {
      md += `### Target Distribution
${activeVerts.map((v) => `| ${v.name} | ${v.w}% |`).join("\n")}

`;
    }
    md += `---

`;
  }

  // ── Advisor Panel ──
  if (sections.scoring) {
    md += `## Team 3: Advisor Panel

### Advisors
| Advisor | Weight | Focus |
|---------|--------|-------|
${activeAdvisors.map((a) => `| \`advisor_${a.id}\` | ${a.w}x | ${a.focus} |`).join("\n")}

`;

    // GTM Advisor deep dive (if GTM advisor is active and has veto)
    if (vetoAdvisors.length > 0) {
      md += `### 🚨 GTM Advisor Deep Dive

**The GTM Advisor has VETO POWER on acquisition strategy.**

An idea with a weak or unrealistic GTM plan cannot score above 75%, regardless of how good the product is.

**GTM Advisor evaluates:**

#### 1. Time to First Paying Customer
| Rating | Timeline | Example |
|--------|----------|---------|
| 🟢 Excellent | <30 days | Paid ads + landing page, launch sequence |
| 🟡 Good | 30-60 days | Community seeding + launch + early ads |
| 🟠 Slow | 60-120 days | Content marketing + SEO starting to work |
| 🔴 Too Slow | 120+ days | Pure SEO, no paid/organic acceleration |

#### 2. Acquisition Channel Reality Check
| Channel | AI-Automatable? | Speed | Best For |
|---------|-----------------|-------|----------|
| **Paid Social (Meta/TikTok)** | ✅ AI creative | Days | B2C, visual products |
| **Google Search Ads** | ✅ High | Days | High-intent searches |
| **Product Hunt/Launch** | ✅ Medium | Day 1 spike | Dev tools, productivity |
| **Reddit/Communities** | ✅ Needs authenticity | 2-4 weeks | Niche audiences |
| **Influencer/UGC** | ✅ AI outreach | 2-4 weeks | Consumer, lifestyle |
| **Newsletter sponsors** | ✅ High | 1-2 weeks | Targeted niches |
| **Programmatic SEO** | ✅ AI content | 2-4 months | Long-term, high volume |
| **Viral/PLG** | ⚠️ Product-dependent | Varies | Products with share triggers |
${bizTouch === "self_serve" ? '| **Cold email/LinkedIn** | ❌ Not allowed | — | — |' : '| **Cold outreach** | ⚠️ Use sparingly | Weeks | B2B |'}
${bizType === "physical" ? '| **Amazon/Etsy Marketplace** | ✅ AI listings | Days | Physical products |\n| **Shopify + Ads** | ✅ AI creative | Days | E-commerce |' : ""}

#### 3. Required GTM Stack (Must Be Specific)
Every idea MUST specify actual tools for:

**Ad Creative & Testing:**
- Creatify, AdCreative.ai, Pencil → AI-generated ads
- Foreplay → Ad inspiration library
- Motion, Triple Whale → Analytics

**Landing & Conversion:**
- Framer, Webflow → Fast landing pages
- Unbounce → A/B testing
- Testimonial.to → Social proof

**Outreach & Partnerships:**
- Instantly, Smartlead → Email sequences (partnerships, not cold sales)
- SparkToro → Audience research
- Passionfroot → Creator/newsletter partnerships

**Content & SEO (for long-term, not primary):**
- Surfer, Clearscope → SEO optimization
- Byword, Letterdrop → Programmatic content

**Launch Coordination:**
- Prelaunch.com → Waitlist
- Notion + Zapier → Launch checklist automation

`;
    }

    // Scoring criteria
    md += `### Scoring Criteria
| Criteria | Weight | 1 (Low) | 3 (Medium) | 5 (High) |
|----------|--------|---------|------------|----------|
`;
    const criteriaDescriptions: Record<string, [string, string, string]> = {
      gtm: ["Vague/SEO-only/slow", "Mixed channels, 60-day path", "Specific stack, <30 day path"],
      auto: ["<80% / high-touch", "80-90%", "95-99% hands-off"],
      econ: [`Unclear path to $${revenue.toLocaleString()}`, "Viable", `Clear math to $${revenue.toLocaleString()}`],
      diff: ["Me-too", "Some angle", "Clear moat"],
      build: ["Complex", "Moderate", `<2 weeks, ${L.invest[bizInvest]}`],
    };
    for (const c of criteria) {
      const desc = criteriaDescriptions[c.k] || ["Low", "Medium", "High"];
      md += `| **${c.n}** | ${c.w}% | ${desc[0]} | ${desc[1]} | ${desc[2]} |\n`;
    }

    md += `
### Hard Gates
| Condition | Result |
|-----------|--------|
${bizTouch === "self_serve" ? "| Requires ANY manual sales/demos | → REJECT |\n" : ""}| GTM is "SEO" only with no fast channel | → CAP at 70% |
| No specific GTM tools mentioned | → CAP at 70% |
| Time to first customer >90 days | → CAP at 75% |
| No differentiation in saturated market | → CAP at 75% |

---

`;
  } else {
    md += `## Scoring ✗ (excluded — no structured scoring applied)

Ideas will be generated but not scored with the advisory panel.

---

`;
  }

  // ── Quality Rules ──
  md += `## Quality Rules

### Red Flags (Penalties)
${bizTouch === "self_serve" ? "- Requires any manual sales → REJECT\n" : ""}- Acquisition "figure out later" → -20%
- Single acquisition channel → -10%
- Oversaturated market → -15%
${bizTouch === "self_serve" || bizTouch === "low" ? "- High-touch onboarding → -15%\n" : ""}
### Bonuses
- Blue ocean (competitor research) → +10%
- Self-serve viral mechanics → +5%
- Poor UX in market → +5%
- Multiple automated channels → +5%
${activePrinciples.some((p) => p.t.toLowerCase().includes("quantif")) ? "- Clear, quantifiable ROI for the customer (pay X, save 10X) → +10%\n" : ""}${activePrinciples.some((p) => p.t.toLowerCase().includes("impact")) ? "- Creates meaningful social impact for underserved group → +5%\n\n" : ""}
---

`;

  // ── Iteration Protocol ──
  md += `## Iteration Protocol

**Trigger:** Score ${deckCut - 15}%-${deckCut - 1}% AND advisor has specific suggestion
**Max:** 1 round

1. Advisors provide specific fix
2. Founders produce v2
3. Re-score (no further iteration)
4. If v2 ≥ ${deckCut}% → auto pitch deck

---

`;

  // ── Daily Execution ──
  md += `## Daily Execution

### Pre-Flight Check (Run FIRST, Every Time)

\`\`\`bash
# 1. Confirm correct project directory
pwd

# 2. Verify pitch-decks folder exists
ls pitch-decks/

# 3. Check/create today's daily folder
mkdir -p research/daily/$(date +%Y-%m-%d)
\`\`\`

### Sequence
1. **Pre-Flight** (2 min): Run verification above
2. **Inbox** (10 min): Process ideas + research${pendingFeed.length > 0 ? " + input feed items" : ""}
3. **Trend Scouts** (30 min): Diverse verticals
4. **Competitor Scout** (20 min): Research competition
5. **Creative Founders** (60 min): Generate **${ideasPer} diverse ideas**
6. **Advisor Panel** (60 min): Evaluate all
7. **Iteration** (30 min if triggered)
8. **🚨 PITCH DECKS** (20 min): Generate decks for **TOP 6** ideas scoring ${deckCut}%+ (see below)
9. **Synthesis** (15 min): Generate daily report
10. **Post-Flight** (2 min): Verify all files in correct locations

---

`;

  // ── Pitch Deck Generation ──
  md += `## ⚠️ MANDATORY: Automatic Pitch Deck Generation

### TOP 6 Rule

After scoring is complete, automatically generate pitch decks for the **TOP 6 highest-scoring ideas that are ${deckCut}% or above**.

| Score | Status | Action |
|-------|--------|--------|
| 90%+ | GREENLIT | ✅ **Include in TOP 6** |
| ${deckCut}-89% | STRONG CANDIDATE | ✅ **Include in TOP 6** |
| ${deckCut - 15}%-${deckCut - 1}% | — | Iterate first, no deck unless reaches ${deckCut}%+ |
| <${deckCut - 15}% | — | No deck |

### Selection Process
1. List ALL ideas scoring ${deckCut}%+
2. Sort by score (highest first)
3. Select TOP 6 for deck generation
4. Note remaining ${deckCut}%+ ideas in daily report as "Deck Deferred"

---

## Wave-Based Deck Generation (Context Management)

### Wave 1: Top 3 Decks
1. Read \`/templates/pitch-deck-template.md\`
2. Generate decks for ideas ranked #1, #2, #3
3. Save each to \`/pitch-decks/[name]-deck.html\`
4. **CHECKPOINT:** Verify 3 decks created:
   \`\`\`bash
   ls -la pitch-decks/ | tail -5
   \`\`\`

### Wave 2: Next 3 Decks
1. Re-read template (fresh context)
2. Generate decks for ideas ranked #4, #5, #6
3. Save each to \`/pitch-decks/[name]-deck.html\`
4. **CHECKPOINT:** Verify all 6 decks created

### Validation Pass (After Both Waves)
For each deck, verify:
- [ ] File exists in \`/pitch-decks/\`
- [ ] Has exactly 12 slides (\`class="slide"\` appears 12 times)
- [ ] Uses light theme (\`background: #ffffff\`)
- [ ] No dark theme colors (\`#0d1117\` appears 0 times)
- [ ] No gradients (\`linear-gradient\` appears 0 times)

**If any deck fails:** Regenerate that specific deck.

---

## Post-Flight Verification

\`\`\`bash
# Verify decks in correct location
echo "=== Pitch Decks ===" && ls pitch-decks/*-deck.html | tail -10

# Check for misplaced decks
echo "=== Checking for misplaced decks ===" && find research/daily -name "*-deck.html" 2>/dev/null

# Verify today's daily folder
echo "=== Today's Output ===" && ls research/daily/$(date +%Y-%m-%d)/
\`\`\`

---

`;

  // ── File Locations ──
  md += `## ⚠️ CRITICAL: File Locations

### Project Root
\`\`\`
~/Projects/ai-business-research/
\`\`\`

### Where to Put Files

| File Type | Location | Example |
|-----------|----------|---------|
| **Pitch Decks** | \`~/Projects/ai-business-research/pitch-decks/\` | \`pitch-decks/neuromoment-deck.html\` |
| **Daily Reports** | \`~/Projects/ai-business-research/research/daily/YYYY-MM-DD/\` | \`research/daily/${date}/daily_report.html\` |
| **JSON Data** | \`~/Projects/ai-business-research/research/daily/YYYY-MM-DD/\` | \`research/daily/${date}/ideas.json\` |

### Pitch Decks — ALWAYS in Root \`/pitch-decks/\`

\`\`\`
~/Projects/ai-business-research/
├── pitch-decks/                    ← ALL pitch decks go here (ROOT LEVEL)
│   ├── [idea-name]-deck.html
│   └── ...
├── research/
│   └── daily/
│       └── YYYY-MM-DD/
│           ├── ideas.json
│           ├── scores.json
│           └── daily_report.html
├── templates/
│   ├── pitch-deck-template.md
│   ├── reflection-commands.md
│   └── ai-insights-template.md
├── inbox/
│   ├── ideas/
│   └── research/
└── idea_memory_active.json
\`\`\`

### ❌ DO NOT:
- Put pitch decks inside \`/research/daily/YYYY-MM-DD/pitch-decks/\`
- Create a pitch-decks subfolder inside the daily folder
- Put pitch decks anywhere other than the root \`/pitch-decks/\` folder

### ✅ DO:
- Save ALL pitch decks to \`~/Projects/ai-business-research/pitch-decks/\`
- Use filename format: \`[idea-name-lowercase]-deck.html\`
- Generate a deck for EVERY idea scoring ${deckCut}%+

---

`;

  // ── Daily Report Format ──
  md += `## Daily Report Format

\`\`\`
╔══════════════════════════════════════════════════════════════╗
║          AI BUSINESS OPPORTUNITY REPORT - [DATE]             ║
╚══════════════════════════════════════════════════════════════╝

[If ≥90%: 🔥 GREENLIT: [Name] - [X]% - [One-liner]]
[If ${deckCut}-89%: ⭐ STRONG CANDIDATE: [Name] - [X]% - [One-liner]]

══════════════════════════════════════════════════════════════
IDEAS SUMMARY (All ${ideasPer} ideas)
══════════════════════════════════════════════════════════════

| # | Idea | Vertical | Conviction | Status |
|---|------|----------|------------|--------|
| 1 | Name | [vertical] | X% | [GREENLIT/STRONG/Iterate/Pass] |

══════════════════════════════════════════════════════════════
🚨 PITCH DECKS GENERATED TODAY
══════════════════════════════════════════════════════════════
**Total qualifying ideas (${deckCut}%+):** [X]
**Decks generated (TOP 6):** [X]
**Decks deferred:** [X]
**Location:** ~/Projects/ai-business-research/pitch-decks/

══════════════════════════════════════════════════════════════
ELEVATOR PITCHES (All ideas 60%+)
══════════════════════════════════════════════════════════════

### 1. [IDEA NAME] - [X]% conviction
**Vertical:** [e.g., Consumer/Health]
**One-liner:** [Pitch]
**Revenue:** [Model]
**Path to $${revenue.toLocaleString()}:** [Specific calculation]
**Automation:** [X]% | **Acquisition:** [Channels]
**Why it could work:** [Key insight]
**Key risk:** [Main concern]
\`\`\`

---

`;

  // ── Idea Memory ──
  md += `## Idea Memory System

### Files
- \`idea_memory_active.json\` — Ideas from last 60 days (loaded every run)
- \`idea_memory_archive.json\` — Older ideas (not loaded, reference only)

### Deduplication
Before generating new ideas, check against memory:
- Same core concept = skip
- Similar but different angle = note as "variation of X"
- Same vertical, different solution = OK
${novelty >= 70 ? '\n**NOVELTY ENFORCEMENT:** If an idea is a variation of something in memory, it MUST have a clearly different business model, audience, or core mechanism to qualify. Simple rebranding or minor pivots do not count as novel.' : ""}

---

`;

  // ── Commands ──
  md += `## Execution Commands

### Daily
\`\`\`
Run daily discovery protocol
\`\`\`

### Manual
\`\`\`
Score this idea: [idea description]
Generate pitch deck for [idea name]
\`\`\`

### AI Insights (Analyze all pitch decks)
\`\`\`
Generate AI Insights Report
\`\`\`
Analyzes all pitch decks and generates strategic recommendations report.
- Reads decks from \`~/Projects/deck-viewer/public/decks/\`
- Reads metadata from \`~/Projects/deck-viewer/data/decks-meta.json\`
- Outputs to \`~/Projects/ai-business-research/research/insights/insights-report.html\`
- See \`/templates/ai-insights-template.md\` for full instructions

### Reflection (Read template first)
\`\`\`
Run advisor panel debrief
Analyze idea patterns from past [X] days
Run improvement analysis on near-miss ideas
Run founders training session
Run system retrospective for past [X] days
\`\`\`

---

*v4.0 — Generated by IdeaForge · ${date} · TOP 6 deck cap, wave-based generation, novelty at ${novelty}%*
`;

  return md;
}
